---
- hosts: all
  become: true
  tasks: 
    - name: Install Docker for Ubuntu
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker for CentOS
      dnf:
        name: docker-ce
        state: present
      when: ansible_distribution == "CentOS"

    - name: Enable Docker socket
      systemd:
        name: docker.socket
        enabled: yes

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create Dockerfile
      copy:
        content: |
          FROM ubuntu:latest
          
          RUN apt-get update && \
              apt-get install -y apache2 mysql-server
          
          EXPOSE 80 3306
 
          CMD ["apache2ctl", "-D", "FOREGROUND]
        dest: /home/gonzales/Dockerfile
      when: ansible_distribution == 'CentOS'  
